#!/bin/bash

cd ..

curl -L -o qemu-aarch64-static https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/qemu-aarch64-static && chmod +x qemu-aarch64-static
curl -L -o qemu-arm-static https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/qemu-arm-static && chmod +x qemu-arm-static

# Register qemu-*-static for all supported processors except the 
# current one, but also remove all registered binfmt_misc before
docker run --rm --privileged multiarch/qemu-user-static:register --reset

find .
echo "PWD: $PWD"

docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
